#!/usr/bin/env bash
# =============================================================================
# update-cloudflare-ips.sh
# Refreshes /etc/nginx/snippets/cloudflare-ips.conf with the current
# Cloudflare IP ranges and reloads Nginx.
#
# Schedule via cron (weekly is sufficient — CF rarely changes these):
#   0 3 * * 0 /usr/local/bin/update-cloudflare-ips.sh >> /var/log/update-cf-ips.log 2>&1
# =============================================================================

set -euo pipefail

SNIPPET="/etc/nginx/snippets/cloudflare-ips.conf"
TMP=$(mktemp)

echo "# Auto-generated by update-cloudflare-ips.sh on $(date -u)" > "$TMP"
echo "# Source: https://www.cloudflare.com/ips/" >> "$TMP"
echo "" >> "$TMP"
echo "# IPv4" >> "$TMP"

curl -fsSL https://www.cloudflare.com/ips-v4 | while IFS= read -r cidr; do
    echo "allow ${cidr};" >> "$TMP"
done

echo "" >> "$TMP"
echo "# IPv6" >> "$TMP"

curl -fsSL https://www.cloudflare.com/ips-v6 | while IFS= read -r cidr; do
    echo "allow ${cidr};" >> "$TMP"
done

echo "" >> "$TMP"
echo "deny all;" >> "$TMP"

# Only replace if the new file looks valid (at least 10 allow lines)
ALLOW_COUNT=$(grep -c "^allow" "$TMP" || true)
if [[ "$ALLOW_COUNT" -lt 10 ]]; then
    echo "ERROR: Fetched IP list looks too short (${ALLOW_COUNT} entries). Aborting." >&2
    rm "$TMP"
    exit 1
fi

cp "$TMP" "$SNIPPET"
rm "$TMP"

# Test Nginx config before reloading
if nginx -t 2>/dev/null; then
    systemctl reload nginx
    echo "OK: Cloudflare IPs updated (${ALLOW_COUNT} ranges) and Nginx reloaded."
else
    echo "ERROR: Nginx config test failed after updating IPs. Manual review needed." >&2
    exit 1
fi
